project:
  type: website

website:
  title: "Essays on Data Science"
  open-graph: true
  sidebar:
    style: "floating"
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
