project:
  type: website
  render:
    - docs/
website:
  title: "Essays on Data Science"
  open-graph: true
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    toc: true

jupyter: essays-on-data-science
execute:
  freeze: auto # re-render only when source changes
  cache: true

callout-appearance: simple
